import discord


embedTank = discord.Embed(title='Tank Loadout')
embedTank.set_thumbnail(url="https://img.finalfantasyxiv.com/lds/promo/h/d/rFrCBcRe9YrmPvb4fZkuFksSLw.png")
embedTank.add_field(name = 'Pure Essence of the Indomitable ', value= "Fragment of Fortitude", inline = True)
embedTank.add_field(name = 'Resistance Reraiser', value = "Fragment of Care", inline = False)
embedTank.add_field(name = 'Lost Dispel ', value = "Fragment of Ingenuity", inline = False)
embedTank.add_field(name = 'Lost Perception', value = "Fragment of Observation", inline = False)
embedTank.add_field(name = 'Lost Aethershield', value = "Fragment of Fortitude", inline = False)
embedTank.add_field(name = 'Lost Sacrifice', value = "Fragment of Loss", inline = False)
embedTank.add_field(name = 'Lost Font of Power', value = "Fragment of Sagacity", inline = False)
embedTank.add_field(name = 'Note', value = "Font of Power can be subbed for Lost Blood Rage", inline = False)

embedHealer = discord.Embed(title='Healer Loadout')
embedHealer.set_thumbnail(url="https://img.finalfantasyxiv.com/lds/promo/h/e/V5xx3kfnREBO-2xWbTUW2Csy_Q.png")
embedHealer.add_field(name = 'Pure Essence of the Divine ', value= "Forgotten Fragment of Divinity", inline = True)
embedHealer.add_field(name = 'Resistance Reraiser', value = "Fragment of Care", inline = False)
embedHealer.add_field(name = 'Lost Steelsting / Spellforge ', value = "Fragment of Ingenuity", inline = False)
embedHealer.add_field(name = 'Lost Banner of Solemn Clarity', value = "Forgotten Fragment of Resolve", inline = False)
embedHealer.add_field(name = 'Lost Shell / Protect', value = "Forgotten Fragment of Caution", inline = False)
embedHealer.add_field(name = 'Lost Reflect', value = "Forgotten Fragment of Support", inline = False)
embedHealer.add_field(name = 'Lost Arise', value = "Forgotten Fragment of Compassion", inline = False)
embedHealer.add_field(name = 'Note', value = "1 healer will bring Lost Shell, the other one Lost Protect", inline = False)

embedMelee = discord.Embed(title='Melee Loadout')
embedMelee.set_thumbnail(url="https://img.finalfantasyxiv.com/lds/promo/h/7/9muqitiUXEK0W3qnM33Nb7sATk.png")
embedMelee.add_field(name = 'Pure Essence of the Duelist ', value= "Forgotten Fragment of Contention", inline = True)
embedMelee.add_field(name = 'Resistance Reraiser', value = "Fragment of Care", inline = False)
embedMelee.add_field(name = 'Lost Rend Armor ', value = "Forgotten Fragment of Contention", inline = False)
embedMelee.add_field(name = 'Lost Font of Power', value = "Forgotten Fragment of Sagacity", inline = False)
embedMelee.add_field(name = 'Lost Banner of Honored Sacrifice', value = "Forgotten Fragment of Resolve", inline = False)

embedCaster = discord.Embed(title='Caster Loadout')
embedCaster.set_thumbnail(url="https://img.finalfantasyxiv.com/lds/promo/h/X/8Dnf8Wy9IyxIt21y6lrE5atKt0.png")
embedCaster.add_field(name = 'Pure Essence of the Elder ', value= "Forgotten Fragment of Clarity", inline = True)
embedCaster.add_field(name = 'Resistance Reraiser', value = "Fragment of Care", inline = False)
embedCaster.add_field(name = 'Lost Font of Magic ', value = "Forgotten Fragment of Sagacity", inline = False)
embedCaster.add_field(name = 'Lost Cure IV', value = "Forgotten Fragment of Compassion", inline = False)
embedCaster.add_field(name = 'Lost Flare Star', value = "Forgotten Fragment of Clarity", inline = False)
embedCaster.add_field(name = 'Lost Banner of Noble Ends', value = "Forgotten Fragment of Resolve", inline = False)
embedCaster.add_field(name = 'Note', value = "Only 1 (preferably BLM) brings Lost Flare Star", inline = False)

embedRanged = discord.Embed(title='Ranged Loadout')
embedRanged.set_thumbnail(url="https://img.finalfantasyxiv.com/lds/promo/h/t/oWWxUIO2KagIEhDXy0541MRD7M.png")
embedRanged.add_field(name = 'Pure Essence of the Fiendhunter ', value= "Forgotten Fragment of Finesse", inline = True)
embedRanged.add_field(name = 'Resistance Reraiser', value = "Fragment of Care", inline = False)
embedRanged.add_field(name = 'Lost Dervish ', value = "Forgotten Fragment of Finesse", inline = False)
embedRanged.add_field(name = 'Lost Font of Power', value = "Forgotten Fragment of Sagacity", inline = False)

embedSlimes = discord.Embed(title='Slimes')
embedSlimes.add_field(name = 'Mandatory Lost Actions', value= 'Lost Perception', inline = False)
embedSlimes.set_thumbnail(url="https://media.discordapp.net/attachments/865356085396766780/1008546697087033344/slimes1.png")
embedSlimes.add_field(name = "Video Guide", value="https://www.youtube.com/watch?v=-VXCCxiwo1s&ab_channel=VesperXIV", inline = False)
embedSlimes.add_field(name= 'Loot', value= "Two chests are lootable before Trinity Seeker. These include one random Pure Fragment each.", inline = False)

embedGolems = discord.Embed(title='Golems')
embedGolems.add_field(name = 'Mandatory Lost Actions', value= 'Lost Perception', inline = False)
embedGolems.add_field(name = 'General Video Guide', value= "https://youtu.be/mgqUyPQeQ4I")
embedGolems.add_field(name = 'General Text Guide', value= "https://docs.google.com/document/d/1IRgNEjuluguiTTi8MVQcm0pOwnML56kua_dy5R3gTTw/edit", inline = False)
embedGolems.set_thumbnail(url="https://cdn.discordapp.com/attachments/865356085396766780/1009264437737308221/golems.png")
embedGolems.add_field(name= 'Loot', value= "Two chests are lootable before Trinity Seeker. These include one random Pure Fragment each.")

embedTS = discord.Embed(title='Trinity Seeker')
embedTS.add_field(name = 'Mandatory Lost Actions', value= '', inline = False)
embedTS.add_field(name = 'General Video Guide', value= "")
embedTS.set_thumbnail(url="https://cdn.discordapp.com/attachments/865356139146772500/1009269498592907284/TS.png")
embedTS.add_field(name= 'Loot', value= "One chest is lootable after Trinity Seeker. This will drop one Runner’s Plating (Foot Gear) with a small chance to drop an Orderly Runner’s Secrets (Foot Gear).")

embedStigWar = discord.Embed(title='Stigymoloch Warrior')
embedStigWar.add_field(name = 'Mandatory Lost Actions', value= 'Lost Dispel, Lost Perception', inline = False)
embedStigWar.add_field(name = 'General Video Guide', value= "https://youtu.be/qPzm84XkJMM")
embedStigWar.set_image(url="https://cdn.discordapp.com/attachments/865356698448691241/1009271299262132296/stygwar1.png")
embedStigWar.set_thumbnail(url="https://cdn.discordapp.com/attachments/865356698448691241/1009270052761129020/stygwar.png")
embedStigWar.add_field(name= 'Loot', value= "One chest is lootable after the Stygimoloch Warrior. This will drop two random Pure Fragments.")

embedDahu = discord.Embed(title='Dahu')
embedDahu.add_field(name = 'Mandatory Lost Actions', value= '', inline = False)
embedDahu.add_field(name = 'General Video Guide', value= "https://youtu.be/gY8ml1bFqkQ")
embedDahu.set_thumbnail(url="https://cdn.discordapp.com/attachments/865356172403408896/1009270599849361499/dahu.png")
embedDahu.add_field(name= 'Loot', value= "One chest is lootable after Dahu. This will drop two random Pure Fragments.")

embedQG = discord.Embed(title="Queen's Guard")
embedQG.add_field(name = 'Mandatory Lost Actions', value= 'Lost Steelsting, Lost Spellforge, Lost Reflect', inline = False)
embedQG.add_field(name = 'General Video Guide', value= "https://youtu.be/9MXEhVDQyNA?list=PLrrlka4IEnUrNCbXmTEd1Kyu0BkeCIq9p", inline = False)
embedQG.set_thumbnail(url="https://cdn.discordapp.com/attachments/865358906658127912/1009266502236647484/QG.png")
embedQG.set_image(url="https://cdn.discordapp.com/attachments/865358906658127912/1009990745052156055/QG1.png")
embedQG.add_field(name= 'Loot', value= "One chest is lootable after the Queen’s Guards, with one additional chest if the duel was successful. The normal chest rewards one Runner’s Plating (Head Gear) while the duel chest rewards one Runner’s Plating (Hand Gear). Both chests have a chance to drop the upgrade item whole.")

embedPhantom = discord.Embed(title='Phantom')
embedPhantom.add_field(name = 'Mandatory Lost Actions', value= 'Lost Dispel, Lost Banish', inline = False)
embedPhantom.add_field(name = 'General Video Guide', value= "https://youtu.be/gY8ml1bFqkQ?t=180")
embedPhantom.set_thumbnail(url="https://cdn.discordapp.com/attachments/865356895606538250/1009265785287491624/phantom.png")
embedPhantom.add_field(name= 'Loot', value= "One chest is lootable after the Bozjan Phantom. This will drop two random Pure Fragments.")

embedStigLord = discord.Embed(title='Stigymoloch Lord')
embedStigLord.add_field(name = 'Mandatory Lost Actions', value= 'Lost Reflect, Lost Dispel, Lost Perception', inline = False)
embedStigLord.add_field(name = 'General Video Guide', value= "https://youtu.be/SCcZhDHasSk?list=PLrrlka4IEnUrNCbXmTEd1Kyu0BkeCIq9p")
embedStigLord.set_image(url="https://cdn.discordapp.com/attachments/865357150443929620/890047111347966052/Stygian_Tanking.png")
embedStigLord.set_thumbnail(url="https://cdn.discordapp.com/attachments/865357150443929620/1009273657564074095/stiglord.png")
embedStigLord.add_field(name= 'Loot', value= "One chest is lootable after the Stygimoloch Lord. This will drop one Runner’s Plating (Body Gear) with a small chance to drop an Orderly Runner’s Secrets (Body Gear).")

embedTA = discord.Embed(title='Trinity Avowed')
embedTA.add_field(name = 'Mandatory Lost Actions', value= 'Lost Aethershield', inline = False)
embedTA.add_field(name = 'General Video Guide', value= "https://youtu.be/0smRlpWl99Q")
embedTA.add_field(name = 'Hot n Cold slashes explanation', value= "https://www.youtube.com/watch?v=Zj62aLLneus", inline = False)
embedTA.set_image(url="https://cdn.discordapp.com/attachments/865357009201266688/1008537245831139409/avowed.png")
embedTA.set_thumbnail(url="https://cdn.discordapp.com/attachments/865357009201266688/1008540941038129333/avowed2.png")
embedTA.add_field(name= 'Loot', value= "One chest is lootable after Trinity Avowed. This will drop one Runner’s Plating (Leg Gear) with a small chance to drop an Orderly Runner’s Secrets (Leg Gear).")

embedQueen = discord.Embed(title='The Queen')
embedQueen.add_field(name = 'Mandatory Lost Actions', value= 'Lost Aethershield, Lost Dispel, Lost Reflect', inline = False)
embedQueen.add_field(name = 'General Video Guide', value= "https://youtu.be/hm2FnqllMvo")
embedQueen.add_field(name= 'Loot', value= "One chest is lootable after the Queen. This will drop one random Orderly Runner’s Secret upgrade item, the Save the Princess minion, five Pure Fragments of Loss, and one Pure Fragment of Deception.", inline = False)

embedQueen2=discord.Embed(title="Relentless Play", description="During these mini phases, sets of the Queen's Guard will appear and there will be some mechanics to resolve")
embedQueen2.add_field(name="1st Relentless Play", value="Warrior + Gunner", inline=False)
embedQueen2.add_field(name="Warrior", value="Reversal of Forces + Winds of Weight", inline=False)
embedQueen2.add_field(name="Gunner", value="Automatic Turret + Reading + Queen's Shot", inline=False)
embedQueen2.add_field(name="Queen", value="Northswain’s Glow", inline=False)
embedQueen2.add_field(name="Summary", value="Move to safe side, resolve weight (tethered to wind), resolve gunner shot then turret shot", inline=False)
embedQueen2.add_field(name="---------------------------------------------", value="---------------------------------------------", inline=False)
embedQueen2.add_field(name="2nd Relentless Play", value="Knight + Soldier", inline=False)
embedQueen2.add_field(name="Knight", value="Shield Omen", inline=False)
embedQueen2.add_field(name="Soldier", value="Double Gambit + Secrets Revealed", inline=False)
embedQueen2.add_field(name="Queen", value="Judgment Blade 2x", inline=False)
embedQueen2.add_field(name="Summary", value=" Queen + Knight (push to save side) -> Queen + Soldier safe spot", inline=False)
embedQueen2.add_field(name="---------------------------------------------", value="---------------------------------------------", inline=False)
embedQueen2.add_field(name="3rd Relentless Play", value="Knight + Gunner", inline=False)
embedQueen2.add_field(name="Knight", value="Sword/Shield Omen + Optimal Play", inline=False)
embedQueen2.add_field(name="Gunner", value="Automatic Turret", inline=False)
embedQueen2.add_field(name="Queen", value="Nothing", inline=False)
embedQueen2.add_field(name="Summary", value="Knight -> Turrets", inline=False)
embedQueen2.add_field(name="---------------------------------------------", value="---------------------------------------------", inline=False)
embedQueen2.add_field(name="4th Relentless Play", value="Warrior + Soldier", inline=False)
embedQueen2.add_field(name="Warrior", value="Bombslinger + Reversal of Forces + Above Board", inline=False)
embedQueen2.add_field(name="Soldier", value="Fiery Portent OR Icy Portent", inline=False)
embedQueen2.add_field(name="Queen", value="Heavens Wrath", inline=False)
embedQueen2.add_field(name="Summary", value="move to be pushed on appropriate bomb, ajust position ONLY after Fiery Portent (if it is fire)!", inline=False)
embedQueen2.add_field(name="---------------------------------------------", value="---------------------------------------------", inline=False)
embedQueen2.add_field(name="5th Relentless Play", value="ALL", inline=False)
embedQueen2.add_field(name="Soft Enrage", value="Coordinate aethershield + healers with banner active (activate it after push of 4th Relentless Play)", inline=False)
embedQueen2.add_field(name="---------------------------------------------", value="---------------------------------------------", inline=False)
embedQueen2.set_footer(text="Relentless Play")
